# Claude Mother System - システム設定ファイル
# 全エージェント統合システムの設定を管理

# 基本設定
environment: "development"  # development, testing, staging, production
system_name: "Claude Mother System"
version: "1.0.0"

# GitHub設定（環境変数から上書き推奨）
github_token: ""  # GITHUB_TOKEN環境変数を設定
repo_name: ""     # REPO_NAME環境変数を設定

# ログ設定
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file_path: "logs/system.log"
max_log_file_size_mb: 100
log_retention_days: 30

# リソース制限
max_concurrent_competitions: 3
default_gpu_budget_hours: 50.0
default_api_calls_limit: 10000
max_execution_time_hours: 72.0

# エージェント個別設定
agent_configs:
  planner:
    enabled: true
    max_concurrent_tasks: 2
    timeout_minutes: 30
    retry_attempts: 3
    resource_limits:
      max_memory_mb: 2000
      max_planning_iterations: 10
    custom_settings:
      enable_advanced_scheduling: true
      default_strategy: "balanced"

  analyzer:
    enabled: true
    max_concurrent_tasks: 3
    timeout_minutes: 45
    retry_attempts: 3
    resource_limits:
      max_api_calls_per_hour: 1000
      max_concurrent_searches: 5
    custom_settings:
      enable_deep_analysis: true
      grandmaster_pattern_limit: 50
      arxiv_search_enabled: true
      web_search_enabled: true

  executor:
    enabled: true
    max_concurrent_tasks: 5
    timeout_minutes: 180
    retry_attempts: 2
    resource_limits:
      max_gpu_hours: 20.0
      max_parallel_experiments: 3
    custom_settings:
      enable_multi_cloud: true
      default_optimization_strategy: "bayesian"
      hyperparameter_tuning_enabled: true

  monitor:
    enabled: true
    max_concurrent_tasks: 1
    timeout_minutes: 10
    retry_attempts: 5
    resource_limits:
      monitoring_frequency_seconds: 30
      max_alert_rate_per_hour: 20
    custom_settings:
      enable_predictive_alerts: true
      detailed_performance_tracking: true

  retrospective:
    enabled: true
    max_concurrent_tasks: 1
    timeout_minutes: 60
    retry_attempts: 2
    resource_limits:
      max_analysis_depth: "comprehensive"
      max_insights_per_competition: 20
    custom_settings:
      enable_knowledge_base_updates: true
      automatic_best_practices_extraction: true

# セキュリティ設定
api_rate_limit_per_hour: 5000
max_issue_creation_per_hour: 100
enable_audit_logging: true

# パフォーマンス設定
monitoring_interval_seconds: 30
health_check_interval_seconds: 300
auto_scaling_enabled: false

# 通知設定
notification_channels: []  # 将来的にSlack、Discord等の通知チャンネル
alert_thresholds:
  cpu_usage_percent: 80.0
  memory_usage_percent: 85.0
  gpu_usage_percent: 90.0
  error_rate_percent: 5.0
  api_rate_limit_remaining: 100
  success_rate_threshold: 0.8

# 実験・機能フラグ
enable_experimental_features: false
feature_flags:
  enable_advanced_monitoring: true
  enable_auto_scaling: false
  enable_predictive_analysis: true
  enable_multi_competition: true
  enable_experimental_techniques: false
  enable_automated_deployment: false
  enable_cost_optimization: true
  enable_performance_benchmarking: true

# 競技別設定
competition_settings:
  default:
    min_score_improvement: 0.05
    target_ranking_percentile: 0.1
    max_gpu_budget_hours: 40.0
  
  tabular:
    preferred_techniques:
      - "gradient_boosting_ensemble"
      - "multi_level_stacking"
      - "feature_engineering_automated"
    max_gpu_budget_hours: 30.0
  
  computer_vision:
    preferred_techniques:
      - "neural_network"
      - "ensemble_cnn"
      - "transfer_learning"
    max_gpu_budget_hours: 60.0
  
  nlp:
    preferred_techniques:
      - "transformer_ensemble"
      - "bert_fine_tuning"
      - "multi_model_stacking"
    max_gpu_budget_hours: 50.0

# クラウドプラットフォーム設定
cloud_platforms:
  kaggle:
    enabled: true
    priority: 1
    weekly_gpu_limit: 30.0
    reliability_score: 0.95
  
  colab:
    enabled: true
    priority: 2
    daily_gpu_limit: 12.0
    reliability_score: 0.85
  
  paperspace:
    enabled: true
    priority: 3
    monthly_gpu_limit: 6.0
    reliability_score: 0.90

# データベース・ストレージ設定
storage:
  knowledge_base_path: "data/knowledge_base.json"
  technique_patterns_path: "data/technique_patterns.json"
  competition_history_path: "data/competition_history.json"
  model_cache_path: "cache/models/"
  log_archive_path: "logs/archive/"
  
  # 自動クリーンアップ設定
  auto_cleanup_enabled: true
  max_cache_size_gb: 10.0
  cache_retention_days: 30